### ISSUE TITLE
Fresh Project

### ISSUE THREAD

**Issue by MohammedBadrLMG** [cloudflare/cloudflare-gcp#25]
Hi,
I am getting below error trying to push the data from google bucket into bigquery

 textPayload: "AssertionError [ERR_ASSERTION]: missing path
    at Module.require (module.js:595:3)
    at require (internal/module.js:11:18)
    at gcsbq (/srv/index.js:9:18)
    at /worker/worker.js:825:24
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)"  
 timestamp: "2019-10-28T19:44:59.898Z" 

Your fast support is highly appreciated.  

Regards,
Badr.

**Comment by shagamemnon** [comment]
Try again when you have a chance @MohammedBadrLMG
